import React, { Component } from 'react';
import { Link } from 'react-router-dom';
import Search from './Search';
import styled from 'styled-components';

const BarW = styled.div`
  display: flex;
  height: 6rem;
  position: relative;
  width: 100vw;
  margin: 0 -50vw;
  left: 50%;
  right: 50%;
  background: linear-gradient(to left, rgba(92,37,141,0.1), rgba(67,137,162, 0.1));
  border-bottom: 1px solid rgba(100, 65, 164, 0.3);
`;

const LogoW = styled.div`
  display: flex;
  flex-flow: column;

  & > p {
    font-family: 'Open Sans', sans-serif;
    color: rgba(100, 65, 164, 1);
    font-size: 0.8em;
    margin: -3px 0 0 0;
  }
`;

const Logo = styled(Link)`
  font-family: 'Lato', sans-serif;
  font-size: 2.3em;
  font-weight: 900;
  letter-spacing: 5px;
  margin: 0;
  color: black;
  text-decoration: none;

  & > img {
    padding-right: 7px;
  }
`;
const Tagline = styled.p`
  
`;

const InternalW = styled.div`
  display: flex;
  width: 70%;
  margin: 0 auto;
  justify-content: space-between;
  align-items: center;
`;

class TopBar extends Component {
  render() {
    return (
      <BarW>
        <InternalW>
          <LogoW>
            <Logo to={'/'}>P<img src="https://static-cdn.jtvnw.net/emoticons/v1/88/1.0" alt="PogChamp!"/>GTRACKER</Logo>
            <p>Highlights generated by chat activity</p>
          </LogoW>
        </InternalW>
      </BarW>
    );
  }
}

export default TopBar;