import React, { Component } from 'react';
import Search from './Search';
import styled from 'styled-components';

const BarW = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin: 20px 0 30px 0;
`;

const LogoW = styled.div`
  display: flex;
  flex-flow: column;

  & > p {
    font-family: 'Open Sans', sans-serif;
    color: rgba(100, 65, 164, 1);
    font-size: 0.9em;
    margin: -3px 0 0 0;
  }
`;

const Logo = styled.h3`
  font-family: 'Lato', sans-serif;
  font-size: 2.3em;
  font-weight: 900;
  letter-spacing: 5px;
  margin: 0;

  & > img {
    padding-right: 7px;
  }
`;
const Tagline = styled.p`
  
`;

class TopBar extends Component {
  render() {
    return (
      <BarW>
        <LogoW>
          <Logo>P<img src="https://static-cdn.jtvnw.net/emoticons/v1/88/1.0" alt="PogChamp!"/>GTRACKER</Logo>
          <p>Highlights generated by chat activity</p>
        </LogoW>
        <Search />
      </BarW>
    );
  }
}

export default TopBar;